# -*- coding: utf-8 -*-
"""三木晋吉 資料アーカイブ — 収録項目の原本。
ここを編集して rebuild.py を実行すると index.html と sitemap.xml が更新される。
EVENTS=PDF項目 / IMAGES=画像項目 / VIDEOS=動画項目。
en は [本文(英), 検索用キーワード(英)] の2要素。"""

EVENTS = [
dict(path='講演・登壇/ny-tomonkai-2024-general-meeting.pdf',
 keys=[], date='2024-06-14', group='講演・登壇',
 title='ニューヨーク稲門会 2024年度総会（乾杯の発声）',
 note='2024年6月14日、ハーバードクラブ・オブ・ニューヨークで開かれた早稲田大学ニューヨーク稲門会の2024年度総会の記録10点。三木晋吉が乾杯の発声を務めました。校友会旗を掲げた会場での役員のご挨拶、記念品の贈呈、壇上での乾杯、テーブルでの歓談、参加者およそ80名の集合写真、そして二次会へ向かうミッドタウンの夜まで。会場となったハーバードクラブは1894年開館のニューヨーク市指定歴史建造物です。ご一緒した方々のお名前は伏せています。',
 en=["Ten photographs from the 2024 general meeting of the Waseda University New York Alumni Association, held at the Harvard Club of New York City on 14 June 2024, where Shinkichi Miki proposed the toast. The set runs from arrival at the club — a New York City landmark opened in 1894 — through the officers' remarks before the alumni banner, the presentation of a gift, the toast from the floor, conversation at the tables, the group photograph of some eighty members, and midtown at night on the way to the second party. The names of those pictured are withheld.",
     'waseda university new york alumni association ny tomonkai 2024 general meeting harvard club of new york city 14 june 2024 toast kanpai shinkichi mike miki 早稲田 稲門会']),

dict(path='事業統合/grand-guardian-tokio-marine-myanmar-jv-2019.pdf',
 keys=[], date='2019-12-18', group='事業統合',
 title='ミャンマー Grand Guardian Tokio Marine 合弁設立（2019年）',
 note='東京海上日動火災保険と、シュエタング・グループ傘下の Grand Guardian Insurance Holding によるミャンマーでの損害保険合弁会社「Grand Guardian Tokio Marine General Insurance（GGITM）」設立の記録14点。三木晋吉が東京海上アジア統括として設立を主導しました。2019年4月30日にヤンゴンのパンパシフィック・ホテルで両社の調印式が行われ、同年11月28日にミャンマー当局の設立認可を取得（東京海上日動が15％出資）、12月に日本生命との生命保険合弁 Grand Guardian Nippon Life とあわせて営業を開始しました。収録内容は、2019年3月10日のシュエダゴン・パゴダ（全景、参拝、献水）、4月30日の調印式での署名と調印書の交換、12月3日のオフィス開設に伴うテープカットと開所式、そして Business Launch Celebratory Dinner の舞台、ミャンマーと日本の民族衣装をまとった出演者の皆さまとの記念撮影、会場での記念撮影、両社関係者による集合写真。ミャンマー国営の Myanmar Digital News は12月4日付で開業式典を報じ、出席者として東京海上日動火災保険代表 Shinkichi Miki の名を記しています。ご一緒した方々のお名前は伏せています。',
 en=['Fourteen records of the establishment of Grand Guardian Tokio Marine General Insurance (GGITM), the Myanmar general insurance joint venture between Tokio Marine & Nichido Fire Insurance and Grand Guardian Insurance Holding, part of the Shwe Taung Group. Shinkichi Miki led the venture from the Tokio Marine Asia side. The signing ceremony was held at the Pan Pacific Yangon on 30 April 2019; the Myanmar authorities granted approval to establish the company on 28 November 2019, with Tokio Marine & Nichido taking a 15 per cent stake, and the business began in December together with Grand Guardian Nippon Life, the life insurance joint venture. The set holds the Shwedagon Pagoda on 10 March 2019 — the stupa at night, a portrait in the precinct and an offering of water — the signing and the exchange of documents on 30 April, the ribbon cutting and opening of the office on 3 December, and from the Business Launch Celebratory Dinner the stage, portraits with performers in Myanmar and Japanese dress, portraits with colleagues, and the group photograph of both parties. Myanmar Digital News reported the launch on 4 December 2019, naming Shinkichi Miki among those present as the representative of Tokio Marine & Nichido Fire Insurance. The names of those pictured are withheld.',
     'grand guardian tokio marine general insurance ggitm myanmar joint venture 2019 shwe taung group yangon pan pacific signing ceremony 30 april 2019 ribbon cutting office opening business launch nippon life shinkichi mike miki tokio marine asia shwedagon pagoda']),

dict(path='事業統合/tokio-marine-safety-insurance-merger-2018-2019.pdf',
 keys=[], date='2019-06-04', group='事業統合',
 title='東京海上セーフティー・インシュランス 発足 — タイ事業の統合（2018-2019年）',
 note='タイ国東京海上火災保険と、タイの保険大手セーフティー・インシュランスの統合の記録7点。三木晋吉が統合のリーダーとして推進しました。買収は2018年6月に発表され、2019年6月4日に合併新会社の名称を「東京海上セーフティー・インシュランス」とすることが公表、タイ保険委員会事務局（OIC）の承認を経て2020年初めに統合が完了しました。新会社は3年以内に収入保険料217億バーツ、純利益11億バーツを目標に掲げています。収録内容は、2561年（2018年）6月の事業方針記者会見、幹部の集合写真、2019年4月30日の全社集会（会場全体と参加者の様子）、2019年6月4日の記者会見後に撮影された新経営陣の記念撮影、時事通信社「時事速報」2019年6月5日付の報道、そして2019年12月20日のタウンホールミーティング「Foster a sustainable future」。The Nation紙も「Insurers merge as Tokio Marine Safety Insurance」として報じています（本サイトの外部掲載欄からご覧いただけます）。ご一緒した方々のお名前は伏せています。',
 en=['Seven records of the merger of Tokio Marine Insurance (Thailand) with Safety Insurance, one of Thailand\'s major general insurers — a integration that Shinkichi Miki led. The acquisition was announced in June 2018; on 4 June 2019 the name of the merged company was announced as Tokio Marine Safety Insurance, and the integration completed in early 2020 following approval by Thailand\'s Office of Insurance Commission. The new company set out targets of 21.7 billion baht in gross written premium and 1.1 billion baht in net profit within three years. The set holds the June 2018 business-strategy press conference, a group portrait of the management team, the all-staff meeting of 30 April 2019, the portrait of the new leadership taken after the press conference of 4 June 2019, the JIJI Press bulletin of 5 June 2019 reporting the merger, and the town hall meeting of 20 December 2019 under the banner "Foster a sustainable future". The Nation also carried the story as "Insurers merge as Tokio Marine Safety Insurance"; the link is in the external coverage section of this site. The names of those pictured are withheld.',
     'tokio marine safety insurance thailand merger integration 2018 2019 acquisition shinkichi mike miki leader office of insurance commission oic gross written premium town hall foster a sustainable future jiji press the nation bangkok']),

dict(path='記念写真/waseda-gakuin-nonaka-sensei-shaonkai-2019.pdf',
 keys=[], date='2019-02-09', group='記念写真',
 title='早稲田大学高等学院 野中久武先生 謝恩会（2019年）',
 note='2019年2月9日に開かれた早稲田大学高等学院 英語科 野中久武先生の謝恩会の記録14点。三木晋吉は1983年の学院卒業生として出席しました。壇上での学年ごとの記念撮影、会場いっぱいの参加者およそ200名による全体集合写真、テーブルでの記念撮影、早稲田大学応援部によるチアリーディングと演舞、先生ご自身がスクリーンに当時の写真を映しながら語られる場面、肩を組んでの校歌斉唱、そして万歳三唱まで。本アーカイブに収録している2017年11月の「グローバル社会と、学院と、これから2017」パネルディスカッションは、この野中先生が教え子5名と語る企画で、三木晋吉もパネリストとして登壇したものです。ご一緒した方々のお名前は伏せています。',
 en=['Fourteen photographs from the celebration held on 9 February 2019 in honour of Hisatake Nonaka, who taught English at Waseda University Senior High School. Shinkichi Miki attended as a member of the class of 1983. The set holds the group portraits by year on stage, the whole-hall photograph of some two hundred former students, table portraits, the cheerleading and cheering squad of Waseda University, the teacher speaking with photographs from his teaching years on the screen behind him, the school song sung arm in arm, and the closing banzai. The panel discussion of November 2017 also held in this archive was hosted by the same teacher with five of his former students, Shinkichi Miki among them. The names of those pictured are withheld.',
     'waseda university senior high school gakuin nonaka hisatake teacher celebration 9 february 2019 tokyo alumni school song cheerleading class of 1983 謝恩会 野中久武']),

dict(path='掲載記事/thailand-insurance-2019-tokio-marine-asia.pdf',
 keys=[], date='2019-01-01', group='掲載記事',
 title='Thailand Insurance 誌 2019年 特集「21年目のタイ保険業界に何が起きるか」',
 note='タイの保険専門誌 Thailand Insurance（นิตยสารไทยแลนด์อินชัวรันส์）創刊21年目の特集記事。2562年（2019年）以降のタイ保険業界の展望を論じる。金利環境と家計消費、監督当局の規制強化、業界再編・M&Aの加速、生命保険と損害保険の垣根の変化などを取り上げる。東京海上アジア 常務取締役 三木晋吉（ชินคิจิ ไมค์ มิกิ）が、東南アジア市場の潜在力、とりわけCLMV諸国とメコン地域の成長性についてコメント。',
 en=['Feature in Thailand Insurance magazine marking its 21st year, on what lies ahead for the Thai insurance industry from 2019: interest rates and household spending, tighter regulation, accelerating consolidation and M&A, and the blurring line between life and non-life. Shinkichi Mike Miki, Managing Director of Tokio Marine Asia, comments on the potential of the Southeast Asian market and particularly the growth of the CLMV countries and the Mekong region.',
     'thailand insurance magazine 2019 industry outlook consolidation m&a regulation tokio marine asia managing director clmv mekong southeast asia']),

dict(path='受賞・表彰/asia-insurance-industry-awards-2018-singapore.pdf',
 keys=[], date='2018-10-01', group='受賞・表彰',
 title='22nd Asia Insurance Industry Awards 2018（シンガポール）',
 note='Asia Insurance Review 主催「22nd Asia Insurance Industry Awards 2018」（シンガポール）の記録2点。東京海上アジア 常務取締役 三木晋吉は2018年・2019年の2年にわたり同アワードの審査員を務めました。記念プレートの授与と、壇上でのスピーチ。2018年10月開催。正確な日付は不明です。ご一緒した方々のお名前は伏せています。',
 en=['Two photographs from the 22nd Asia Insurance Industry Awards, organised by Asia Insurance Review and held in Singapore in October 2018: the presentation of a commemorative plaque, and Shinkichi Miki speaking from the podium. As Managing Director of Tokio Marine Asia he served on the panel of judges for the awards in both 2018 and 2019. The exact date is not known. The names of those pictured are withheld.',
     'asia insurance industry awards 2018 22nd singapore asia insurance review panel of judges tokio marine asia managing director gala plaque podium']),

dict(path='社内行事/tmith-shanai-hyosho-2016-2018.pdf',
 keys=[], date='2018-07-28', group='社内行事',
 title='タイ国東京海上火災保険 社内表彰 2016-2018',
 note="年次行事以外の社内表彰の記録3点。「TMITH GOT TALENT」プロジェクトの表彰（2016年1月11日・Ratchapruek Room）、関係者への表彰状授与（写真データの記録日は2016年7月28日）、そして「ROCK 'N ROLL」をテーマとしたパーティーでの表彰（会場の掲示は7月8日、写真データの記録日は2018年7月28日）。後半2点は正確な開催日が確認できていません。ご一緒した方々のお名前は伏せています。",
 en=["Three records of internal awards outside the annual events: the award for the TMITH Got Talent project on 11 January 2016 in the Ratchapruek Room; the presentation of certificates to colleagues and partners, the photograph dated 28 July 2016 in its file data; and an award at a Rock 'n Roll themed party, whose banner reads 8 July and whose file data is dated 28 July 2018. The exact dates of the latter two are not confirmed. The names of those pictured are withheld.",
     'tmith got talent 2016 internal award certificate presentation rock n roll party tokio marine insurance thailand bangkok staff recognition']),

dict(path='社内行事/tokio-marine-asia-regional-growth-strategy-meeting-2018.pdf',
 keys=[], date='2018-06-29', group='社内行事',
 title='東京海上アジア Regional Growth Strategy Meeting（2018年6月29日）',
 note='2018年6月29日に開かれた東京海上アジア（Tokio Marine Asia）の Regional Growth Strategy Meeting の記録5点。スクリーンには「To Be a Good Company」のスローガンと TOKIO MARINE INSURANCE GROUP のロゴ、そして「Regional Growth Strategy Meeting／June 29th, 2018／Tokio Marine Asia」と映されています。アジア各国の拠点から集まった70名を超える参加者の集合写真、スクリーンを背にしたチームでの記念撮影、そして夜の懇親会でのスナップ3点。三木晋吉のネームタグには TMA（Singapore）とあり、シンガポールの東京海上アジア（Tokio Marine Asia）のマネージング・ディレクターとしてアジア統括を務めていた時期にあたります。参加者の服装や名札が示すとおり、タイ、インドネシア、フィリピン、シンガポール、日本など各国のメンバーが一堂に会した会議でした。ご一緒した方々のお名前は伏せています。',
 en=['Five photographs from the Regional Growth Strategy Meeting of Tokio Marine Asia, held on 29 June 2018. The screen carries the group\'s slogan "To Be a Good Company" with the Tokio Marine Insurance Group mark, and the title "Regional Growth Strategy Meeting — June 29th, 2018 — Tokio Marine Asia". The set holds the group portrait of the seventy-odd colleagues who came in from offices across Asia, a team photograph before the screen, and three frames from the reception that evening. Shinkichi Miki\'s name badge reads TMA (Singapore): at this time he was Managing Director of Tokio Marine Asia in Singapore, heading the region. The dress and badges of those present show a meeting that drew members together from Thailand, Indonesia, the Philippines, Singapore and Japan among others. The names of those pictured are withheld.',
     'tokio marine asia regional growth strategy meeting 29 june 2018 singapore tma head of asia to be a good company tokio marine insurance group regional offices reception shinkichi mike miki head of asia 東京海上アジア 戦略会議']),

dict(path='社内行事/tmith-kekki-taikai-2018-agency.pdf',
 keys=[], date='2018-03-30', group='社内行事',
 title='タイ国東京海上火災保険 代理店決起大会 2018（KEKKI TAIKAI 2018）',
 note='2018年3月30日に開催された代理店決起大会「KEKKI TAIKAI 2018」の記録8点。舞台裏、ステージでの出し物、背景幕での記念撮影、そして翌31日にタイの正装で撮影した記念写真。正装での記念写真は、コロニアル様式の洋館の前での少人数と大人数の集合、および会場の背景幕の前での撮影。三木晋吉社長にとって最後の決起大会となりました（後任の発表は同月28日）。ご一緒した方々のお名前は伏せています。',
 en=["Eight photographs from Kekki Taikai 2018, the annual agency rally of Tokio Marine Insurance (Thailand), held on 30 March 2018: backstage, a stage performance, group portraits at the backdrop, and photographs in Thai formal dress taken the following day — before a colonial-style villa and at the event backdrop. It was the last such rally of Shinkichi Miki's tenure as President; his successor had been announced on 28 March. The names of those pictured are withheld.",
     'kekki taikai 2018 agency rally tokio marine insurance thailand bangkok annual meeting thai formal dress stage backdrop']),

dict(path='社内行事/tmith-shinnenkai-2018.pdf',
 keys=[], date='2018-03-16', group='社内行事',
 title='タイ国東京海上火災保険 新年会 2018',
 note='2018年3月16日に開催された社員の新年会の記録8点。その年のテーマは「Once upon the time」。ステージ前での記念撮影、テーブルでの集合、仮装した皆さまとの記念写真、会場全景に加え、中華風の装いの方との記念撮影、セーラー服姿の一団による余興の壇上へマイクを持って上がる場面、舞台裏での記念撮影。ご一緒した方々のお名前は伏せています。',
 en=['Eight photographs from the 2018 staff party of Tokio Marine Insurance (Thailand), held on 16 March 2018 under the theme "Once upon the time": portraits in front of the stage, a table group, photographs with colleagues in costume, a view of the hall, a portrait with a colleague in Chinese court dress, Shinkichi Miki taking the stage with a microphone during a sailor-suit performance, and a group photograph backstage. The names of those pictured are withheld.',
     'tmith staff party 2018 once upon the time tokio marine insurance thailand bangkok annual party march 2018 costume stage sailor suit performance']),

dict(path='golf/golf-omoide-lpga-thailand-singapore.pdf',
 keys=[], date='2018-02-01', group='ゴルフ',
 title="ゴルフの思い出 Honda LPGA Thailand・HSBC Women's World Championship",
 note="タイ駐在時代に足を運んだ女子ゴルフトーナメントでの記念写真24点。Honda LPGA Thailand（チョンブリ・シアムカントリークラブ）の練習日・ラウンド・大会レセプション、およびHSBC Women's World Championship（シンガポール）でのもの。2016年大会10周年を記念したガラでの太鼓の演舞、プロアマ戦でサインをいただいたHonda LPGA Thailandのキャップを手にした一枚、2017年・2018年のラウンドで各ホールの表示板の前での記念撮影、レセプションでの記念撮影、そして大会記念のキャディバッグまで。2017年のプロアマ戦の様子は、ご一緒した選手ご本人がSNSに投稿されており、その投稿へのリンクを本サイトの外部掲載欄に置いています。ご一緒した選手の皆さまのお名前は伏せています。",
 en=["Twenty-four photographs from women's golf tournaments attended during the Thailand years: practice days, rounds and the tournament reception at Honda LPGA Thailand (Siam Country Club, Chonburi), and the HSBC Women's World Championship in Singapore. The set includes the drum performance at the gala marking the tournament's tenth anniversary in 2016, a portrait holding a Honda LPGA Thailand cap signed during the pro-am, portraits at the hole markers during the 2017 and 2018 rounds, portraits at the reception, and the commemorative caddie bag. One of the players posted a group photograph from the 2017 pro-am on social media; the link to that post is in the external coverage section of this site. The names of the players pictured are withheld.",
     "golf memories honda lpga thailand siam country club chonburi hsbc women's world championship singapore pro-am 10th anniversary gala 2016 2017 2018 caddie bag signed cap"]),

dict(path='記念写真/thailand-motor-show-2014-2017.pdf',
 keys=[], date='2017-12-01', group='記念写真',
 title='タイのモーターショー（2014-2017年）',
 note='タイで開催された自動車展示会を訪れた際の記録14点。自動車保険を主力とする損害保険会社の経営者として、各社の新型車と市場の動きを見て回ったものです。2014年11月18日の三菱「ALL NEW TRITON」の展示にはじまり、2016年3月22日には会場全景、ポルシェ911 GT3 Cup、MINI／BMW、マツダ、いすゞ、スズキ、スバル、トヨタと各社のブースを回りました。ホンダ「All-new BR-V」の発表ステージも収めています。2017年12月1日には三菱「GT PHEV CONCEPT」のお披露目前に同社の方と記念撮影、ホンダ・シビックのブースやレクサス・ヒュンダイ側の通路で東京海上の同僚の皆さまと並んでいます。当時のタイ国東京海上火災保険社長 三木晋吉。ご一緒した方々のお名前は伏せています。',
 en=["Fourteen photographs from visits to motor shows in Thailand between 2014 and 2017, made as the head of a general insurance company whose largest line was motor — a chance to see each maker's new models and where the market was heading. The set opens with the Mitsubishi All New Triton on 18 November 2014, then 22 March 2016 across the halls: a wide view of the floor, a Porsche 911 GT3 Cup, the MINI and BMW stand, and the Mazda, Isuzu, Suzuki, Subaru and Toyota booths. It also holds the launch stage for the Honda All-new BR-V. On 1 December 2017 Shinkichi Miki was photographed with a Mitsubishi executive before the unveiling of the GT PHEV Concept, and with colleagues from Tokio Marine at the Honda Civic stand and in the aisle by Lexus and Hyundai. The names of those pictured are withheld.",
     'bangkok international motor show thailand motor expo 2014 2016 2017 mitsubishi triton gt phev concept honda br-v civic isuzu suzuki mazda subaru toyota mini bmw porsche 911 gt3 cup tokio marine insurance thailand shinkichi miki']),

dict(path='講演・登壇/waseda-gakuin-panel-2017-global-society.pdf',
 keys=[], date='2017-11-11', group='講演・登壇',
 title='早稲田大学高等学院 パネルディスカッション「グローバル社会と、学院と、これから2017」',
 note='2017年11月11日、早稲田大学高等学院 講堂で開催されたパネルディスカッションの告知資料、当日の記録12点、および学院広報誌の掲載誌面4点。英語科教諭 野中久武氏が教え子5名と語る100分。パネリストは亀山渉（早稲田大学教授）、小松庸人（外務省）、菅野幹雄（日本経済新聞社）、松本晋一（味の素）、三木晋吉（東京海上日動火災保険タイランド社長・1983年学院卒）。写真は登壇の前後に母校を歩いた記録で、人工芝の校庭での記念撮影、渡り廊下、部室で麻雀に興じる在校生たちとの一場面、秋の校舎とグラウンド、体育館でバスケットボールに興じる生徒たち、校内案内図の前での歓談、銀杏並木での集合写真、そして終了後の懇親会——鍋を囲んでのテーブルでの記念撮影、ビールでの乾杯、店の前での一枚まで。あわせて、学院の広報誌『Gakuzatsu』第65号「ボクらの学院。」に特集として掲載された誌面4点（表紙、特集扉、パネリスト発言のページ2点）を収めています。同特集は「野中久武が教え子5人と語る100分のパネルディスカッション」の全文起こしです。なお学院は2017年10月30日に本イベントを公式サイトで告知しており、その告知資料が本項目の1ページ目にあたります。同資料は現在、学院のサイトからは削除されています。同じ野中先生の謝恩会（2019年2月9日）も本アーカイブに収めています。ご一緒した方々のお名前は伏せています。',
 en=['The announcement for the panel discussion "Global Society, the School, and What Comes Next 2017", held in the auditorium of Waseda University Senior High School on 11 November 2017, together with twelve photographs from the day and four pages of the school magazine feature. Hisatake Nonaka, who had taught English at the school for 38 years, spoke for a hundred minutes with five of his former students: a Waseda University professor, a foreign ministry official, a Nikkei commentator, an executive at Ajinomoto, and Shinkichi Miki, then President of Tokio Marine Insurance (Thailand) and a member of the class of 1983. The photographs follow the panellists around their old school before and after the event — the artificial turf ground, the walkways, a club room where current pupils were playing mahjong, the autumn campus, the gymnasium during basketball, the campus map, a group portrait under the ginkgo trees, and the gathering afterwards — the table around the hotpot, a toast over beers, and a last frame on the street outside. Four pages of Gakuzatsu No. 65, the school magazine, are also included: it carried the full transcript of the discussion as a cover feature, and the set holds the cover, the opening spread listing the panellists, and two pages of the exchange. The school announced the event on its website on 30 October 2017 — that announcement is the first page of this item, and it is no longer served from the school website. The celebration held for the same teacher in February 2019 is also in this archive. The names of those pictured are withheld.',
     'waseda university senior high school gakuin panel discussion global society 2017 nonaka hisatake alumni class of 1983 shinkichi miki campus visit ginkgo gymnasium 11 november 2017 gakuzatsu vol 65 school magazine transcript 学雑 ボクらの学院']),

dict(path='受賞・表彰/oic-prime-ministers-insurance-awards-2560-2017.pdf',
 keys=[], date='2017-09-22', group='受賞・表彰',
 title="คปภ. Prime Minister's Insurance Awards 2560（2017年）受賞 — 2年連続",
 note="タイ保険委員会事務局（สำนักงาน คปภ. / OIC）が主催する「รางวัลประกันภัยดีเด่นครบวงจร（Prime Minister's Insurance Awards）」を2560年（2017年）9月22日に受賞した際の記録10点。前年2559年（2016年）に続く2年連続受賞です。壇上での授与に続き、会場に設けられた和のしつらえの自社ブースでトロフィーを手にした記念撮影、社員一同との撮影、展示会場の様子、ブースのスタッフとの記念撮影、そして花束の贈呈まで。プミポン国王陛下の服喪期間中にあたり、参列者は黒の装いです。当時のタイ国東京海上火災保険社長 三木晋吉。ご一緒した方々のお名前は伏せています。",
 en=["Ten photographs from 22 September 2017, when Tokio Marine Insurance (Thailand) received the Prime Minister's Insurance Awards (รางวัลประกันภัยดีเด่นครบวงจร) for the year 2560, presented by Thailand's Office of Insurance Commission (คปภ.) — the second year running, after 2559 (2016). The set runs from the presentation on stage to the company's Japanese-styled exhibition booth, where Shinkichi Miki, then President, was photographed with the trophy, with colleagues and with the booth staff, along with views of the exhibition hall and the presentation of a bouquet. The date falls within the mourning period for His Majesty King Bhumibol Adulyadej, and those present are dressed in black. The names of those pictured are withheld.",
     'prime ministers insurance awards office of insurance commission oic thailand 2560 2017 consecutive second year award trophy exhibition booth bangkok tokio marine insurance thailand president 22 september 2017']),

dict(path='掲載記事/a-day-bulletin-504-2017-tokio-marine-thailand-mike-miki.pdf',
 keys=[], date='2017-09-18', group='掲載記事',
 title='a day BULLETIN 第504号 特集インタビュー「To Be a Good Company」',
 note='タイの週刊フリーマガジン a day BULLETIN 第504号（2017年9月18日発行）の特集インタビュー全4ページ。同誌の発行部数はタイ国内で25万部。東京海上日動火災保険（タイランド）社長 三木晋吉（Shinkichi Mike Miki）。米国・日本・フィリピン・タイでの勤務経験を踏まえた企業文化の違い、「To Be a Good Company」の three pillars、マリン保険とメコン諸国への事業展開、宮本武蔵に学ぶ意思決定について。表紙・pp.10-15。',
 en=['Cover feature interview, "To Be a Good Company," in a day BULLETIN No. 504, a weekly free magazine distributed across Thailand with a circulation of 250,000 copies, dated 18 September 2017. Shinkichi Mike Miki, President of Tokio Marine Insurance (Thailand), on differences in corporate culture across the United States, Japan, the Philippines and Thailand, the three pillars of "To Be a Good Company," marine insurance and expansion into the Mekong countries, and decision-making learned from Miyamoto Musashi. Cover and pp. 10-15.',
     'bangkok weekly free magazine circulation 250,000 copies thailand cover feature interview the challenge shinkichi mike miki president tokio marine insurance thailand marine insurance mekong miyamoto musashi']),

dict(path='記念写真/kinen-shashin-office-2010s.pdf',
 keys=[], date='2017-09-18', group='記念写真',
 title='記念写真 執務室にて（2010年代）',
 note='執務室で撮影した記念写真7点。東京海上の社内誌に掲載された日本リーグ時代の選手名鑑のページを手にしたもの、および a day BULLETIN 第504号「良い会社」の誌面を手にした記録です。同誌は2017年9月18日の発行で、その後オフィスでは同僚たちがそれぞれ誌面を手にして写真を撮りました。サインを入れた誌面2部を掲げての一枚（9月26日）、タイ語紙に掲載された記事とクリスタルのトロフィーを並べた2点（10月6日）、誌面と一枚の写真を手にした執務室での一枚（10月12日）、そして窓辺で誌面を手にした一枚。撮影時期の詳細が不明なものも含みます。ご一緒した方々のお名前は伏せています。',
 en=['Seven photographs taken in the office: one with a page from a Tokio Marine in-house magazine listing the squad from his years in Japan\'s national basketball league, and six with the issue of a day BULLETIN No. 504 carrying the cover line "To Be a Good Company". The magazine was published on 18 September 2017, and colleagues took turns holding it up around the office in the weeks that followed — two signed copies held aloft on 26 September, two frames on 6 October pairing the Thai-language coverage with the crystal award, a portrait on 12 October with the issue and a photograph in hand, and one taken at the window. The dates of some of the photographs are not known. The names of those pictured are withheld.',
     'office photographs tokio marine in-house magazine basketball squad listing a day bulletin 504 good company bangkok 2017 signed copy crystal award thai newspaper coverage colleagues 執務室']),

dict(path='掲載記事/a-day-bulletin-504-2017-photo-session-behind-the-scenes.pdf',
 keys=[], date='2017-08-11', group='掲載記事',
 title='a day BULLETIN 第504号 撮影記録と反響',
 note='2017年8月11日にバンコクで行われた a day BULLETIN 第504号 表紙・特集インタビューの撮影セッションの記録。同誌はタイ全土に25万部を発行する週刊フリーマガジンで、第504号の特集タイトルは表紙に掲げられた「To Be a Good Company」。スタジオでのポートレート撮影、東京海上グループのワールドワイド・ネットワーク図を背にしたカット、執務室での撮影風景、誌面に使われたオフィスでのポートレート。あわせて同年9月18日の発行後、BTS車内やバンコク市内の飲食店で誌面が読まれている様子、10月7日に飲食店でサイン入りの誌面を手にした記念撮影、11月24日にタイ国東京海上火災保険の支店受付に誌面が額装して飾られている様子、および2024年のニューズウィーク日本版掲載時の反響を収録。全14点。ご一緒した方々のお名前は伏せています。',
 en=['Fourteen images around the cover and feature interview of a day BULLETIN No. 504 — "To Be a Good Company" — a weekly free magazine distributed across Thailand with a circulation of 250,000 copies, shot in Bangkok on 11 August 2017: studio portraits, a frame against the Tokio Marine Group worldwide network map, the shoot in his office, and the office portrait used in the magazine. Also included are scenes of the issue being read on the BTS and in Bangkok restaurants after publication on 18 September, a portrait taken in a restaurant on 7 October with the signed copy held up, the spread framed and hung at the reception desk of a Tokio Marine Insurance (Thailand) branch on 24 November, and later reactions to his 2024 appearance in Newsweek Japan. The names of those pictured are withheld.',
     'photo session behind the scenes bangkok cover shoot to be a good company circulation 250,000 copies thailand free magazine studio portrait tokio marine worldwide network bts skytrain 2017 newsweek japan 2024 signed copy restaurant']),

dict(path='社内行事/tmith-kekki-taikai-2017-agency.pdf',
 keys=[], date='2017-03-31', group='社内行事',
 title='タイ国東京海上火災保険 代理店決起大会 2017（KEKKI TAIKAI 2017 AGENCY AWARDS）',
 note='2017年3月31日に開催された代理店決起大会「KEKKI TAIKAI 2017 AGENCY AWARDS」の記録9点。鏡開き、舞台裏でトロフィーを手にしたカット、出演者の皆さまとの記念撮影、代理店の皆さまとの集合写真、開演前の舞台前でダンサーのお二人との記念撮影、会場でのご来賓との記念撮影。ご一緒した方々のお名前は伏せています。',
 en=["Nine photographs from Kekki Taikai 2017, the agency rally and agency awards of Tokio Marine Insurance (Thailand), held on 31 March 2017: the sake-barrel opening, a backstage moment with a trophy, portraits with the evening's performers, group photographs with the agents, a portrait with two of the dancers by the stage before the show, and a portrait with a guest at the venue. The names of those pictured are withheld.",
     'kekki taikai 2017 agency awards tokio marine insurance thailand bangkok annual rally kagami biraki trophy performers group photograph 31 march 2017']),

dict(path='王室関連/royal-mourning-king-bhumibol-2017.pdf',
 keys=[], date='2017-03-24', group='王室関連',
 title='タイ王宮にてプミポン国王陛下に拝礼（2017年）',
 note='2016年10月13日に崩御されたプミポン国王陛下（ラーマ9世）に拝礼した際の記録8点。2017年3月24日、タイ国東京海上火災保険の一行が王宮を訪れ、白い花輪を捧げました。男性はタイの正装（白）に喪章、女性は黒の喪服を着用。御真影と白い供花が設けられたオフィスビルのロビーでの記念撮影から、王宮敷地内での全体集合写真、男性一同・女性一同の記念撮影まで。当時のタイ国東京海上火災保険社長 三木晋吉。ご一緒した方々のお名前は伏せています。',
 en=['Eight photographs from 24 March 2017, when a delegation from Tokio Marine Insurance (Thailand) went to the Grand Palace in Bangkok to pay their respects to His Majesty King Bhumibol Adulyadej (Rama IX), who had passed away on 13 October 2016, and to lay a white wreath. The men are in Thai formal white dress with black mourning armbands, the women in black mourning dress. The set runs from portraits before the memorial display in an office building lobby to the group photographs in the palace grounds. Shinkichi Miki was then President of the company. The names of those pictured are withheld.',
     'king bhumibol adulyadej rama ix mourning grand palace bangkok 24 march 2017 tokio marine insurance thailand wreath thai formal white dress mourning armband respects']),

dict(path='社内行事/tmith-shinnenkai-2017-masquerade.pdf',
 keys=[], date='2017-03-17', group='社内行事',
 title='タイ国東京海上火災保険 新年会 2017（MASQUERADE PARTY）',
 note='2017年3月17日に開催された社員の新年会「TMITH 2017 MASQUERADE PARTY」の記録13点。仮装での余興、長年勤続者の表彰（Long Service Award）、仮装コンテストの表彰、参加者の集合写真。三木晋吉社長も仮装して壇上に立ちました。会場入口での牛の着ぐるみ姿の皆さまとの記念撮影、ステージの背景幕（17.03.2017）、豹柄の衣装での余興、会場での皆さまとの記念撮影も収めています。ご一緒した方々のお名前は伏せています。',
 en=['Thirteen photographs from the TMITH 2017 Masquerade Party, the staff party of Tokio Marine Insurance (Thailand), held on 17 March 2017: performances in costume, the Long Service Awards, prizes for the costume contest, group portraits, colleagues in cow onesies at the entrance, the stage backdrop dated 17.03.2017, a leopard-print stage turn, and portraits around the ballroom. Shinkichi Miki took the stage in costume himself. The names of those pictured are withheld.',
     'tmith masquerade party 2017 staff party tokio marine insurance thailand bangkok long service award costume contest march 2017']),

dict(path='掲載記事/nna-thailand-2017-02-tokio-marine-agency-sales.pdf',
 keys=[], date='2017-02-17', group='掲載記事',
 title='The Daily NNA タイ版 2017年2月17日「東京海上、代理店販売を強化」',
 note='アジア経済情報紙NNAタイ版の一面記事。タイ国東京海上火災保険 三木晋吉社長へのインタビュー。タイ進出55周年を経て2017年度を飛躍の年と位置づけ、代理店・ブローカー経由の販売チャンネル拡大により売上高80億バーツ（約260億円）を目指す方針を語る。自動車ディーラー経由50%・日系向け45%という売上構成、タイ特有の自動車保険市場についても言及。',
 en=["Front-page article in The Daily NNA (Thailand edition), 17 February 2017. An interview with Shinkichi Miki, President of Tokio Marine Insurance (Thailand), on positioning 2017 as a year of growth after 55 years in the Thai market, expanding distribution through agents and brokers toward a revenue target of THB 8 billion, and the particular character of Thailand's motor insurance market.",
     'front page interview agency broker distribution thailand motor insurance market baht revenue target']),

dict(path='受賞・表彰/tgia-50th-anniversary-2017.pdf',
 keys=[], date='2017-01-01', group='受賞・表彰',
 title='タイ損害保険協会（TGIA）50周年記念式典（2017年）',
 note='タイ損害保険協会（สมาคมประกันวินาศภัยไทย / TGIA）の創立50周年記念式典「50th Anniversary — The Journey of TGIA」の記録2点。壇上での記念撮影と、業界各社が並んだ全体集合写真。会場には「Power of Insurance」として500万バーツの寄付が掲げられています。2017年開催。正確な日付は不明です。ご一緒した方々のお名前は伏せています。',
 en=['Two photographs from the fiftieth anniversary celebration of the Thai General Insurance Association (TGIA), held under the title "50th Anniversary — The Journey of TGIA" in 2017: a group on stage, and a full assembly of the industry, with the association\'s THB 5 million charitable donation displayed under the banner "Power of Insurance." The exact date is not known. The names of those pictured are withheld.',
     'thai general insurance association tgia fiftieth anniversary 2017 the journey of tgia power of insurance donation bangkok ceremony']),

dict(path='寄稿/my-rookie-days-shinnyu-shain-jidai.pdf',
 keys=[], date='2016-12-08', group='寄稿',
 title='寄稿「My Rookie Days（10）私の新入社員時代」',
 note='タイ国東京海上火災保険 三木晋吉による寄稿。1987年入社当時のバブル期の東京、本店営業3部でマスコミ系顧客を担当した日々、日本リーグ・バスケットボール部との両立、興行中止保険や打ち上げ保険といった特殊な保険の設計、アントニオ猪木氏との出会い、そしてスティーブ・ジョブズの「Connecting Dots」に重ねた「ご縁」についてのエッセイ。',
 en=['Essay by Shinkichi Miki, then President of Tokio Marine Insurance (Thailand), on his first years at the company. Tokyo in the bubble era after joining in 1987, serving media clients at the head office, balancing work with the company\'s basketball team in Japan\'s national league, designing unusual covers such as event cancellation insurance, and a reflection on chance connections framed by Steve Jobs\'s "connecting dots."',
     'essay my rookie days tokyo bubble era media clients event cancellation insurance japan national basketball league connecting dots']),

dict(path='記念写真/wat-ceremony-bangkok-2016-tokio-marine-thailand.pdf',
 keys=[], date='2016-11-04', group='記念写真',
 title='バンコク市内の寺院での法要（2016年）',
 note='2016年11月4日、バンコク市内の寺院の本堂で執り行われた法要に参列した際の記録5点。プミポン国王陛下（ラーマ9世）が2016年10月13日に崩御された直後の服喪期間中にあたり、参列者は白のタイ正装（ชุดปกติขาว）に喪章、または黒の喪服を着用しています。ラーマキエンの壁画と天井画に囲まれた本堂の様子、白い供花を供えた本尊、本尊前での記念撮影、そして本堂前での記念撮影まで。当時のタイ国東京海上火災保険社長 三木晋吉。行事の名称は特定できていないため、確認でき次第あらためて記載します。ご一緒した方々のお名前は伏せています。',
 en=['Five photographs from 4 November 2016, at a Buddhist ceremony held in the ordination hall of a temple in Bangkok. The date falls in the mourning period that began with the passing of His Majesty King Bhumibol Adulyadej (Rama IX) on 13 October 2016, and those attending are in Thai formal white dress with mourning armbands or in black mourning dress. The set shows the hall with its Ramakien murals and painted ceiling, the principal Buddha image with white floral offerings, portraits before the image, and a group portrait at the doors. Shinkichi Miki was then President of Tokio Marine Insurance (Thailand). The name of the occasion has not yet been established and will be added once confirmed. The names of those pictured are withheld.',
     'buddhist ceremony temple wat bangkok 4 november 2016 mourning king bhumibol rama ix thai formal white dress ordination hall ubosot tokio marine insurance thailand']),

dict(path='社会貢献/check-dam-tree-planting-2016-tokio-marine-thailand.pdf',
 keys=[], date='2016-10-08', group='社会貢献',
 title='堰堤づくりと植樹のボランティア（2016年）',
 note='2016年10月8日、タイ国東京海上火災保険の社員が参加した森林保全ボランティアの記録6点。前年のナーン県に続く堰堤（ฝาย）づくりの活動で、この年は竹を組んだ堰堤を沢に築きました。青いテントの下での開会に地元の小学生と村の方々が並び、そろいのTシャツで石を運び、竹を組み、完成した堰堤のそばで記念撮影。休憩をはさんで、子どもたちと一緒に苗木を植えました。当時のタイ国東京海上火災保険社長 三木晋吉も参加しています。CEO Thailand誌が「水と森の保全プロジェクト」として紹介した継続的な取り組みにあたります。ご一緒した方々のお名前は伏せています。',
 en=['Six photographs from 8 October 2016, when staff of Tokio Marine Insurance (Thailand) took part in a forest and water conservation volunteer day. Following on from the check dams built in Nan Province the year before, this time bamboo check dams (ฝาย) were built across a stream. The set runs from the opening under a blue awning, where local schoolchildren and villagers lined up alongside the volunteers, through carrying stones and lashing the bamboo into place, a group portrait at the finished dam and a break under the shelter, to planting saplings together with the children. Shinkichi Miki, then President of the company, took part. This is part of the continuing water and forest conservation work described in the CEO Thailand feature also held in this archive. The names of those pictured are withheld.',
     'check dam fai bamboo tree planting 2016 tokio marine insurance thailand csr volunteer forest water conservation schoolchildren saplings october 2016']),

dict(path='受賞・表彰/oic-prime-ministers-insurance-awards-2559-2016.pdf',
 keys=[], date='2016-09-22', group='受賞・表彰',
 title="คปภ. Prime Minister's Insurance Awards 2559（2016年）受賞",
 note="タイ保険委員会事務局（สำนักงาน คปภ. / OIC）が主催する「รางวัลประกันภัยดีเด่นครบวงจร（Prime Minister's Insurance Awards）」を2559年（2016年）9月22日に受賞した際の記録6点。壇上でトロフィーを受け取るタイ国東京海上火災保険 三木晋吉社長、会場のスクリーン、受賞各社の集合写真、会場ロビーでの記念撮影、そしてトロフィーを囲んだ社員一同の記念撮影2点。翌2560年（2017年）にも同賞を受賞し、2年連続受賞となりました。ご一緒した方々のお名前は伏せています。",
 en=["Six photographs from 22 September 2016, when Tokio Marine Insurance (Thailand) received the Prime Minister's Insurance Awards (รางวัลประกันภัยดีเด่นครบวงจร) for the year 2559, presented by Thailand's Office of Insurance Commission (คปภ.). Shinkichi Miki, then President, receives the trophy on stage; the set also holds the hall screen, a group portrait of the year's recipients, a portrait in the venue lobby and two photographs of colleagues gathered around the trophy. The company received the same award again the following year, 2560 (2017). The names of those pictured are withheld.",
     'prime ministers insurance awards office of insurance commission oic thailand 2559 2016 award trophy ceremony bangkok tokio marine insurance thailand president 22 september 2016']),

dict(path='社会貢献/scholarship-ceremony-2559-tokio-marine-thailand.pdf',
 keys=[], date='2016-09-14', group='社会貢献',
 title='奨学金贈呈式 2559年度（タイ国東京海上火災保険）',
 note='タイ社会福祉協議会（สภาสังคมสงเคราะห์แห่งประเทศไทยฯ）との「พิธีมอบทุนการศึกษา ประจำปีการศึกษา 2559」奨学金贈呈式の記録7点。タイ国東京海上火災保険およびタイ国東京海上生命保険が支援したもので、同社が継続して取り組んでいた社会貢献活動のひとつです。演台での挨拶、生徒の皆さんから出席者への花輪の献上、奨学金の授与、目録を持った関係者の記念撮影、生徒と関係者の全体集合写真。最後の1点は同日にオフィスで撮影したガネーシャ像の飾りです。写真データはいずれも2559年（2016年）9月14日の記録で、同日の開催と見られます。ご一緒した方々のお名前は伏せています。',
 en=['Seven records of the scholarship award ceremony for the 2559 (2016) academic year, held with the National Council of Social Welfare of Thailand and supported by Tokio Marine Insurance (Thailand) and Tokio Marine Life Insurance (Thailand): remarks from the podium, garlands offered by the students to the guests, the presentation of the awards, a group portrait with the ceremonial plaque, and a full assembly of students and organisers. The last image is a Ganesha shrine photographed in the office the same day. All the photographs carry the date 14 September 2016 in their file data, taken here to be the day of the ceremony. The names of those pictured are withheld.',
     'scholarship award ceremony 2559 2016 national council of social welfare of thailand tokio marine insurance thailand life insurance corporate social responsibility bangkok students garland podium september 2016']),

dict(path='講演・登壇/press-conference-2559-2016-tokio-marine-thailand.pdf',
 keys=[], date='2016-03-29', group='講演・登壇',
 title='タイ国東京海上火災保険 年次記者会見 2559（2016年）',
 note='2016年3月29日、バンコク市内のホテルで開かれた年次記者会見の記録5点。看板には「งานแถลงข่าว บริษัทโตเกียวมารีนประกันภัย (ประเทศไทย) จำกัด (มหาชน) ประจำปี 2559」（タイ国東京海上火災保険 2559年 記者会見）と掲げられています。壇上で社長 三木晋吉がマイクを持って記者の質問に答える様子、傷害保険・自動車保険・旅行傷害保険・ゴルファー保険・海上運送保険のアイコンを並べた会社案内のバックボードでの記念撮影。The Nation紙は同じ2016年3月29日付で「Tokio Marine Insurance ups focus on infrastructure」としてこの会見を報じています（本サイトの外部掲載欄からご覧いただけます）。ご一緒した方々のお名前は伏せています。',
 en=['Five photographs from the annual press conference of Tokio Marine Insurance (Thailand) held in a Bangkok hotel on 29 March 2016. The banner reads "งานแถลงข่าว บริษัทโตเกียวมารีนประกันภัย (ประเทศไทย) จำกัด (มหาชน) ประจำปี 2559" — the company press conference for the year 2559. Shinkichi Miki, then President, answers questions from the floor with a microphone, and the set also holds portraits at the company backdrop showing the icons for personal accident, motor, travel accident, golfer and marine and transit insurance. The Nation carried its report of the conference, "Tokio Marine Insurance ups focus on infrastructure", on the same day, 29 March 2016; the link is in the external coverage section of this site. The names of those pictured are withheld.',
     'tokio marine insurance thailand annual press conference 2559 2016 bangkok 29 march 2016 shinkichi miki president media briefing infrastructure the nation งานแถลงข่าว โตเกียวมารีนประกันภัย']),

dict(path='社内行事/tmith-kekki-taikai-2016-agency.pdf',
 keys=[], date='2016-03-25', group='社内行事',
 title='タイ国東京海上火災保険 代理店決起大会 2016（KEKKI TAIKAI 2016）',
 note='2016年3月25日に開催された代理店決起大会「KEKKI TAIKAI 2016」の記録27点。一日の流れがほぼそのまま残っています。会場入口の記念撮影ボードでの受付、着物風の衣装のコンパニオンの皆さまとの記念撮影、申年にちなんだ猿のぬいぐるみを手にしたカット、部門ごとの記念撮影、法被姿での鏡開き、2015年度の利益分配（PROFIT SHARING）目録の贈呈、事業方針「Our Business Compass（AGENT）」の説明、代理店の皆さまへの表彰、景品のテレビの授与、バンドとの共演、ご家族へのぬいぐるみの配布、そしてダンスフロアまで。ご一緒した方々のお名前は伏せています。',
 en=['Twenty-seven photographs from Kekki Taikai 2016, the annual agency rally of Tokio Marine Insurance (Thailand), held on 25 March 2016 — very nearly the whole day. Portraits at the photo wall on arrival, with the hostesses in kimono-style dress and with the monkey soft toys marking the year of the monkey, group portraits by department, the sake-barrel opening in happi coats, the presentation of the 2015 profit-sharing certificate, the "Our Business Compass (AGENT)" strategy briefing, awards to the agents, prizes including a television, a turn with the band, soft toys handed to the families who came, and the dance floor. The names of those pictured are withheld.',
     'kekki taikai 2016 agency rally tokio marine insurance thailand bangkok profit sharing 2015 kagami biraki sake barrel awards prizes band families dance floor 25 march 2016']),

dict(path='社内行事/tmith-shinnenkai-2016.pdf',
 keys=[], date='2016-03-04', group='社内行事',
 title='タイ国東京海上火災保険 新年会 2016（TMITH MUSIC FESTIVAL）',
 note='2016年3月4日、Crystal Ballroom で開催された社員の新年会「TMITH MUSIC FESTIVAL」の記録8点。その年のテーマは音楽祭で、ベリーダンスや客室乗務員の扮装など各部門の余興が続きました。舞台で花輪を掛けて労をねぎらう場面も収めています。ご一緒した方々のお名前は伏せています。',
 en=['Eight photographs from the 2016 staff party of Tokio Marine Insurance (Thailand), held at the Crystal Ballroom on 4 March 2016 under the theme "TMITH Music Festival": performances by each department including belly dancing and cabin-crew costumes, portraits at the backdrop, and a garland placed around a colleague\'s neck on stage in thanks. The names of those pictured are withheld.',
     'tmith music festival 2016 staff party tokio marine insurance thailand bangkok crystal ballroom belly dance cabin crew costume garland march 2016']),

dict(path='golf/customer-golf-christmas-party-2015-tokio-marine-thailand.pdf',
 keys=[], date='2015-12-26', group='ゴルフ',
 title='お客様とのゴルフコンペとクリスマスパーティー（2015年）',
 note='2015年12月26日、タイ国東京海上火災保険がお客様をお招きして開催したゴルフコンペと、その夜のクリスマスパーティーの記録6点。朝の受付ではスコアカードと優勝カップを並べた席に運営の皆さまが並び、コースでは同社のバックボードの前とティーグラウンドで記念撮影。青空の広がるフェアウェイも収めています。日が暮れてからは会場を移し、赤と緑のTシャツやサンタの衣装で全員が並んだ記念撮影2点。当時のタイ国東京海上火災保険社長 三木晋吉。ご一緒した方々のお名前は伏せています。',
 en=["Six photographs from 26 December 2015, when Tokio Marine Insurance (Thailand) held a golf competition for its customers, followed by a Christmas party the same evening. The morning registration desk is set out with scorecards and the winner's cup; portraits follow at the company backdrop and on the tee, along with a view down the fairway under a clear sky. After dark the party moved indoors, where everyone gathered in red and green shirts and Santa costumes for two group photographs. Shinkichi Miki was then President of the company. The names of those pictured are withheld.",
     'customer golf competition christmas party 2015 tokio marine insurance thailand bangkok 26 december 2015 santa costume trophy fairway tee']),

dict(path='社会貢献/check-dam-nan-2015-tokio-marine-thailand.pdf',
 keys=[], date='2015-12-19', group='社会貢献',
 title='堰堤づくりボランティア ナーン県（2015年）',
 note='2015年12月19日、タイ北部ナーン県ボークルア郡プーファー地区のバーン・フアイローム集落で行われた堰堤（ฝาย）づくりのボランティア活動の記録9点。プミポン国王陛下の88歳のお誕生日（2015年12月5日）を記念した「โครงการสร้างฝายถวายในหลวง」として、県・財団とともに実施されました。キャンペーン名は「หอบรัก มาห่มป่า」（愛を抱えて森を包みに）。前夜に集落へ到着して防寒具を贈呈し、翌朝に式典、子どもたちへのマフラー掛け、そして森の中での堰堤づくりへ。タイ国東京海上火災保険の社員が参加し、当時の社長 三木晋吉も加わっています。CEO Thailand誌が「水と森の保全プロジェクト」として紹介した活動にあたります。ご一緒した方々のお名前は伏せています。',
 en=['Nine photographs from 19 December 2015, when staff of Tokio Marine Insurance (Thailand) built check dams (ฝาย) at Ban Huai Lom in Phu Fa, Bo Kluea District, Nan Province in northern Thailand. The project was carried out with the province and a foundation to mark the 88th birthday of His Majesty King Bhumibol Adulyadej on 5 December 2015, under the campaign name "หอบรัก มาห่มป่า" — bringing love to wrap the forest. The set runs from the previous evening, when warm clothing was handed over to the village, through the morning ceremony and the scarves given to the children, to the work on the check dams in the forest. Shinkichi Miki, then President of the company, took part. This is the water and forest conservation project mentioned in the CEO Thailand feature also held in this archive. The names of those pictured are withheld.',
     'check dam fai nan province bo kluea phu fa ban huai lom 2015 tokio marine insurance thailand csr volunteer water forest conservation king bhumibol 88th birthday warm clothing scarves village children']),

dict(path='王室関連/sirindhorn-royal-audience-2015-tokio-marine-photos.pdf',
 keys=[], date='2015-11-04', group='王室関連',
 title='シリントーン王女殿下への拝謁 記念写真（2015年11月4日）',
 note='2015年11月4日、シリントーン王女殿下への拝謁の記録2点。会場となった宮殿の前での記念写真と、同日夜に放送されたチャンネル7の王室ニュースをテレビ画面で捉えた一枚（22時28分撮影）。タイ国東京海上火災保険による寄付に対し、王女殿下より表彰を賜りました。三木晋吉は同社の社長として出席しています。放送された映像そのものは本アーカイブの別項目に収めています。ご一緒した方々のお名前は伏せています。',
 en=["Two photographs from the audience granted by Her Royal Highness Princess Maha Chakri Sirindhorn on 4 November 2015: a group portrait before the palace where the audience was held, and a frame of the television carrying Channel 7's Royal Court News that evening, taken at 22:28. The commendation was conferred for a donation by Tokio Marine Insurance (Thailand); Shinkichi Miki attended as President of the company. The broadcast itself is held as a separate item in this archive. The names of those pictured are withheld.",
     'princess maha chakri sirindhorn royal audience 4 november 2015 thailand tokio marine insurance donation commendation palace group portrait channel 7 royal court news television シリントーン王女 拝謁 タイ王室 記念写真']),

dict(path='社内行事/tmith-halloween-party-2015.pdf',
 keys=[], date='2015-10-29', group='社内行事',
 title='タイ国東京海上火災保険 ハロウィンパーティー 2015',
 note='2015年10月29日、バンコクのオフィスで開催されたハロウィンパーティーの記録14点。執務室を飾り付けし、部署ごとに仮装して午後を過ごしました。部門ごとの集合写真、仮装コンテストの表彰状授与、お菓子の配布、タイの正装での集合写真。三木晋吉社長も仮装で参加しています。ご一緒した方々のお名前は伏せています。',
 en=['Fourteen photographs from the Halloween party held in the Bangkok office of Tokio Marine Insurance (Thailand) on 29 October 2015. The floor was decorated and each department came in costume for the afternoon: group portraits by team, the certificate for the costume contest, sweets handed round, and a group in Thai formal dress. Shinkichi Miki joined in costume himself. The names of those pictured are withheld.',
     'halloween party 2015 tokio marine insurance thailand bangkok office costume contest decorations october 2015 staff event']),

dict(path='掲載記事/the-best-biz-thailand-2015-tokio-marine-press-conference.pdf',
 keys=[], date='2015-07-31', group='掲載記事',
 title='The Best Biz Thailand 2015 表紙特集「東京海上グループ タイ事業戦略記者会見」',
 note='2015年7月31日バンコクで開催された東京海上グループの記者会見（Life & Health / Property & Casualty）を伝える表紙特集 pp.8-11。東京海上ホールディングス 永野毅 社長兼CEOが、タイをメコン諸国の中心と位置づけるグループ戦略、2558年から2560年の中期ビジョン「2017 To be a Good Company」の三本柱（Look beyond Profit・Empower our People・Deliver on Commitment）、HCC Insurance Holdings買収、高齢化社会を迎えるタイでの生命保険・損害保険事業について語る。記者会見にはタイ国東京海上火災保険 三木晋吉社長も同席。',
 en=['Cover feature, pp. 8-11, on the Tokio Marine Group press conference held in Bangkok on 31 July 2015 covering Life & Health and Property & Casualty. Tsuyoshi Nagano, President and CEO of Tokio Marine Holdings, on the group\'s strategy with Thailand at the centre of the Mekong countries, the mid-term vision "2017 To be a Good Company" and its three pillars (Look beyond Profit, Empower our People, Deliver on Commitment), the acquisition of HCC Insurance Holdings, and life and non-life business in an ageing Thailand. Shinkichi Miki, President of Tokio Marine Insurance (Thailand), also attended.',
     'the best biz thailand press conference tsuyoshi nagano tokio marine holdings president ceo hcc insurance holdings good company mekong bangkok 2015']),

dict(path='寄稿/my-fair-golf-jcc-nawatani-15th.pdf',
 keys=[], date='2015-06-01', group='寄稿',
 title='寄稿「My Fair Golf」Serial 71 忘れられないあのホール',
 note='バンコク日本人商工会議所（JCC）理事としての寄稿。1996年フィリピン駐在時に始めたゴルフ歴、シンシナティ・ロサンゼルス駐在時代のラウンド、プロゴルファー宮里藍さんから受けた「自然を楽しむ」という助言、そして忘れられないホールとしてナワタニ・ゴルフ・コース15番を挙げる。',
 en=['Essay written as a director of the Japanese Chamber of Commerce, Bangkok. Taking up golf while posted to the Philippines in 1996, rounds played during the Cincinnati and Los Angeles years, advice from a professional golfer on enjoying the natural setting, and the 15th at Nawatani Golf Course as the hole he cannot forget.',
     'essay my fair golf japanese chamber of commerce bangkok philippines cincinnati los angeles nawatani golf course']),

dict(path='社内行事/tmith-kekki-taikai-2015-agency.pdf',
 keys=[], date='2015-03-27', group='社内行事',
 title='タイ国東京海上火災保険 代理店決起大会 2015（KEKKI TAIKAI 2015）',
 note='2015年3月27日に開催された代理店決起大会「KEKKI TAIKAI 2015」の記録9点。鳥居を模したステージに「FIGHT TOGETHER」「STRIVE FOR SUCCESS」を掲げ、会場にはミャンマーのシュエダゴン・パゴダ、タイのワット・プラケオ、カンボジアのアンコール・トム、ラオスのタート・ルアンを並べた記念撮影ボードが設けられました。法被姿での鏡開き、前年度の優績代理店への「TOKIO MARINE AWARD 2014」表彰（傷害保険1,000,000バーツの目録と鳥居型のトロフィー）、そして三木晋吉社長がLEDスーツをまとってダンスチームと登壇したレーザー演出まで。舞台裏で衣装を着付けている場面も収めています。ご一緒した方々のお名前は伏せています。',
 en=['Nine photographs from KEKKI TAIKAI 2015, the annual agency rally of Tokio Marine Insurance (Thailand), held on 27 March 2015. The stage was built as a torii gate carrying the slogans "Fight Together" and "Strive for Success", and the photo wall set out landmarks of the region — Shwedagon Pagoda in Myanmar, Wat Phra Kaew in Thailand, Angkor Thom in Cambodia and Phra That Luang in Laos. The set covers the sake-barrel opening in happi coats, the Tokio Marine Award 2014 for the leading agencies with a one-million-baht personal accident certificate and torii-shaped trophies, and the laser show in which Shinkichi Miki, then President, took the stage in an LED suit with the dance team — including the moment backstage when the suit was fitted. The names of those pictured are withheld.',
     'kekki taikai 2015 agency rally tokio marine insurance thailand bangkok 27 march 2015 tokio marine award 2014 torii stage led suit laser show sake barrel kagamibiraki happi shwedagon wat phra kaew angkor thom phra that luang']),

dict(path='社内行事/tmith-shinnenkai-2015-wonderland.pdf',
 keys=[], date='2015-03-06', group='社内行事',
 title='タイ国東京海上火災保険 新年会 2015（WONDERLAND NIGHT PARTY）',
 note="2015年3月6日に開催された社員の新年会「Wonderland Night Party」の記録9点。その年のテーマは童話の不思議の国で、バルーンアーチを設けた会場入口での出迎えから始まり、三木晋吉社長が白いスーツで壇上に立って挨拶、各部門の仮装による余興、テーブルごとの記念撮影、魔女のマントをまとった一団のステージ登壇、そして仮装コンテスト入賞者へのROYCE'（ロイズ）チョコレートの贈呈まで。タイ国東京海上火災保険の新年会は2015年から2018年まで本アーカイブに収録しています。ご一緒した方々のお名前は伏せています。",
 en=['Nine photographs from the 2015 staff party of Tokio Marine Insurance (Thailand), held on 6 March 2015 under the theme "Wonderland Night Party". The set runs from the balloon arch at the entrance, through Shinkichi Miki addressing the room in a white suit, the performances by each department in costume, table portraits, a large group in witch capes taking the stage, and the presentation of ROYCE\' chocolates as prizes to the costume-contest winners. The staff parties of the company from 2015 to 2018 are all held in this archive. The names of those pictured are withheld.',
     'tmith wonderland night party 2015 staff party shinnenkai tokio marine insurance thailand bangkok costume contest royce chocolate balloon arch witch cape march 2015']),

dict(path='社会貢献/mangrove-planting-ranong-2015-tokio-marine-nichido.pdf',
 keys=[], date='2015-01-26', group='社会貢献',
 title='マングローブ植林活動 タイ・ラノーン県（2015年1月）',
 note='2015年1月26日から30日にかけて、タイ南部ラノーン県で行われた東京海上日動火災保険のマングローブ植林活動の記録9点。東京海上グループのマングローブ植林プロジェクトは1999年に社員の提案から始まったもので、この回は参加者のTシャツにある通り 「15th Anniversary Tokio Marine & Nichido Mangrove Project Thailand, 2000-2015」——タイでの15周年にあたります。本社から参加した Green Volunteers と、タイ国東京海上火災保険の社員が現地で合流しました。植林地はラノーン県のバンガオ（Ban Ngao）。現地の看板には「Thai-Japan Friendship Through Mangrove Planting Project」「Mangrove Forest : Forest for Life」と掲げられ、オイスカ（OISCA タイ）、タイ海洋沿岸資源局（DMCR）、ンガオ・マングローブ保全コミュニティとの協働で、2014年度に5ヘクタール、通算63回目の植林として実施されたことが記されています。収録は、宿舎となったラノーンの Tinidee Hotel の歓迎幕の前での参加者集合写真、スワンナプーム空港での出発、写真展を設えた式典、DMCR の職員とともに川をさかのぼるボート、植林地の看板の前での説明、地元の小学生たちとの記念撮影2点、川岸でのボランティア、そして海に沈む夕陽まで。同プロジェクトは東京海上ホールディングスの公表によれば2025年3月時点で9カ国・累計12,970ヘクタールに達しています。ご一緒した方々のお名前は伏せています。',
 en=['Nine photographs from the mangrove planting activity of Tokio Marine & Nichido Fire Insurance held in Ranong province, southern Thailand, from 26 to 30 January 2015. The group\'s mangrove planting project began in 1999 from a suggestion by its own employees, and this visit marked fifteen years of the work in Thailand — the volunteers\' shirts read "15th Anniversary Tokio Marine & Nichido Mangrove Project Thailand, 2000-2015". Green Volunteers travelling from the Tokyo head office joined staff of Tokio Marine Insurance (Thailand) on site. The planting ground was at Ban Ngao in Ranong: the board there reads "Thai-Japan Friendship Through Mangrove Planting Project" and "Mangrove Forest : Forest for Life", and records five hectares planted for the 2014 season — the sixty-third planting — in coordination with OISCA (Thailand), the Department of Marine and Coastal Resources, and the Ngao Mangrove Conservation Community. The set holds the group portrait beneath the welcome banner at the Tinidee Hotel in Ranong, the departure from Suvarnabhumi airport, the ceremony staged among an exhibition of photographs, the boat upriver with DMCR rangers, the briefing before the site board, two frames with local schoolchildren, the volunteers on the riverbank, and the sun going down over the sea. Tokio Marine Holdings reports the project had reached 12,970 hectares across nine countries as of March 2025. The names of those pictured are withheld.',
     'mangrove planting ranong thailand january 2015 tokio marine nichido green volunteers 15th anniversary 2000-2015 ban ngao oisca dmcr department of marine and coastal resources ngao mangrove conservation community forest for life thai-japan friendship tinidee hotel csr reforestation マングローブ 植林 ラノーン オイスカ']),

dict(path='掲載記事/ceo-thailand-issue115-2015-tokio-marine-thailand.pdf',
 keys=[], date='2015-01-01', group='掲載記事',
 title='CEO Thailand 誌 Issue 115 表紙特集 タイ国東京海上火災保険 三木晋吉社長',
 note='タイのビジネス誌 CEO Thailand Vol.11 Issue 115 の表紙と表紙特集 pp.31-32。「2558年（2015年）の最優秀損害保険会社」特集の表紙に、ムアンタイ、ティップヤ、サイアムシティ各社のトップと並んで登場。本文では損害保険業界トップ3を目指す方針として、2557年（2014年）の直接収入保険料7412百万バーツ・純利益416百万バーツ、2558年は直接収入保険料8.2十億バーツ・10.8%成長の目標を掲げる。運転行動に応じた自動車保険料の見直し、インフラ関連事業への進出、S&PからのA-格付、修理ネットワークの内製化などを語る。あわせて奨学金、水と森の保全プロジェクト、ネパール地震被災者支援といった社会貢献活動を紹介。',
 en=["Cover and cover feature, pp. 31-32, in the Thai business magazine CEO Thailand, Vol. 11 Issue 115. Shinkichi Miki appears on the cover alongside the heads of Muang Thai, Dhipaya and Siam City Insurance for a feature on the leading non-life insurers of 2015. Inside, he sets out the aim of becoming one of the top three non-life insurers in Thailand: direct written premium of THB 7,412 million and net profit of THB 416 million for 2014, with a target of THB 8.2 billion and growth above 10.8% for 2015. He discusses pricing motor cover by driving behaviour, entry into infrastructure business, the company's A- rating from S&P, and bringing repair networks in house, alongside community work including scholarships, a water and forest conservation project, and relief for the Nepal earthquake.",
     'ceo thailand magazine issue 115 cover story top three non-life insurer direct written premium baht standard and poors a- rating infrastructure motor insurance nepal earthquake relief muang thai dhipaya siam city']),

dict(path='掲載記事/wise-thai-shinchoryu-vol43-tokio-marine-thailand.pdf',
 keys=[], date='2015-01-01', group='掲載記事',
 title='WiSE「タイの新潮流」VOL.43 東京海上日動火災保険（タイランド）社長 三木晋吉',
 note='日系企業トップインタビュー連載。「タイ進出50年で最大の変革期。目指すは、業界3位」。タイ国内24支店・日本人駐在員21名を含む約800名体制、インドネシア・インド・タイを東南アジア3大重要拠点とする位置づけ、メコン室の設置とメコン河下流域（タイ・ミャンマー・ラオス・カンボジア）への展開、業界7位から3位への浮上を5年で達成する目標について語る。',
 en=["Interview in WiSE magazine's series on the heads of Japanese companies in Thailand. Shinkichi Miki on the largest period of change in fifty years in the Thai market: a workforce of roughly 800 across 24 branches, Indonesia, India and Thailand as the three key bases in Southeast Asia, a dedicated Mekong unit covering Thailand, Myanmar, Laos and Cambodia, and the goal of moving from seventh to third in the market within five years.",
     'wise new currents in thailand top interview mekong myanmar laos cambodia branches market ranking']),

dict(path='掲載記事/watashi-no-la-tokio-marine-los-angeles-branch.pdf',
 keys=[], date='2013-01-01', group='掲載記事',
 title='インタビュー「私のLA」生まれ故郷のLAで地域・社会に貢献します',
 note='東京海上日動火災保険 米国支店部長兼ロサンゼルス支店長 三木晋吉へのインタビュー。1965年ロサンゼルス生まれ、87年早稲田大学卒業・東京海上火災保険入社、2003年より米国シンシナティ支店長、08年よりロサンゼルス支店長。中学3年で193cm、バスケットボールとの出会いから日本リーグでの9年間、37歳での引退、生まれ故郷LAへの赴任、JBAを通じた地域貢献活動について語る。',
 en=["Interview with Shinkichi Miki, Head of U.S. Branches and Los Angeles Branch Manager for Tokio Marine & Nichido. Born in Los Angeles in 1965, he graduated from Waseda University and joined the company in 1987, became Cincinnati Branch Manager in 2003 and Los Angeles Branch Manager in 2008. He describes reaching 193cm in his third year of junior high, nine years in Japan's national basketball league, retiring from the game at 37, returning to the city of his birth, and community work through the Japan Business Association.",
     'my la interview head of us branches los angeles branch manager born 1965 waseda university 1987 cincinnati japan business association basketball national league']),

dict(path='記念写真/kinen-shashin-1990s-2010s.pdf',
 keys=[], date='2013-01-01', group='記念写真',
 title='記念写真 1990年代-2010年代',
 note='パーティーや会合の折に撮影した記念写真8点。1990年代の東京でのパーティー、および2010年代のロサンゼルス・ビバリーヒルズ駐在時代のもの。ご一緒した方々のお名前は伏せています。',
 en=['Eight photographs taken at parties and gatherings: Tokyo in the 1990s, and the Los Angeles and Beverly Hills years in the 2010s. The names of those pictured are withheld.',
     'commemorative photographs tokyo los angeles beverly hills 1990s 2010s']),

dict(path='受賞・表彰/tokio-marine-us-100th-anniversary-los-angeles-2012.pdf',
 keys=[], date='2012-02-24', group='受賞・表彰',
 title='東京海上 米国進出100周年 記念祝賀会（ロサンゼルス・2012年）',
 note='2012年2月24日、ロサンゼルスの全米日系人博物館（JANM）で開催された東京海上の米国進出100周年記念祝賀会の記録15点。当時のロサンゼルス支店長 三木晋吉。会場全景、演台での挨拶、JANMへの25,000ドルの寄付目録の贈呈、鏡開きと乾杯、1931年のTIME誌などを収めた歴史展示、記念ケーキの入刀。前半8点は The Rafu Shimpo（羅府新報）撮影、後半6点は別のカメラによるものです。同紙の記事「米国進出100周年で祝賀会：顧客や地元社会に感謝」（2012年3月7日）は本サイトの外部掲載欄からご覧いただけます。ご一緒した方々のお名前は伏せています。',
 en=["Fifteen photographs from the celebration marking one hundred years of Tokio Marine in the United States, held at the Japanese American National Museum in Los Angeles on 24 February 2012. Shinkichi Miki was then Los Angeles Branch Manager. The set covers the hall, remarks from the podium, the presentation of a USD 25,000 donation to the museum, the sake-barrel opening and toast, a display case of historical material including a 1931 issue of TIME, and the cutting of the anniversary cake. The first eight are by The Rafu Shimpo; the remainder are from another camera. The paper's report of 7 March 2012 is linked in the external coverage section of this site. The names of those pictured are withheld.",
     'tokio marine nichido united states centenary one hundred years celebration los angeles 2012 japanese american national museum janm donation kagami biraki sake barrel rafu shimpo branch manager little tokyo']),

dict(path='掲載記事/jba-news-2011-10-nisei-week-arigato.pdf',
 keys=[], date='2011-10-01', group='掲載記事',
 title='JBA NEWS 2011年10月号「二世ウィーク・ジャパニーズ・フェスティバル／ARIGATOイベント」',
 note='南加日系商工会議所（JBA）会報。三木ダウンタウン地域部会長がJBAを代表して二世ウィーク開会式で挨拶し、実行委員長マーク・ナカガワ氏へ5000ドルを寄付。あわせて東日本大震災被災者支援への感謝イベント「ARIGATO -Southern California for Supporting Japan Relief」（在ロサンゼルス日本国総領事館主催・日米文化会館ノグチプラザ）を報じる。',
 en=['Newsletter of the Japan Business Association of Southern California. Miki, as chair of the downtown chapter, spoke on behalf of the JBA at the opening ceremony of Nisei Week and presented a $5,000 donation to the festival\'s chairman, Mark Nakagawa. The issue also reports on "ARIGATO — Southern California for Supporting Japan Relief," hosted by the Consulate General of Japan in Los Angeles at Noguchi Plaza.',
     'japan business association newsletter nisei week japanese festival arigato consulate general of japan los angeles japanese american cultural community center noguchi plaza']),

dict(path='掲載記事/rafu-shimpo-2011-07-nisei-week-candidates.pdf',
 keys=[], date='2011-07-19', group='掲載記事',
 title='The Rafu Shimpo 2011年7月19日「Nisei Week Candidates Revealed」',
 note='ロサンゼルスの日系紙 羅府新報の記事。第71回二世ウィーク日本祭（2011年8月13-21日・リトルトーキョー）開会式の報道。Japan Business Association（JBA）を代表し三木晋吉が二世ウィーク財団のMark Nakagawa会長に5000ドルの寄付を贈呈した写真を掲載。',
 en=['Article in The Rafu Shimpo, the Japanese American newspaper of Los Angeles, covering the opening of the 71st Nisei Week Japanese Festival in Little Tokyo, 13-21 August 2011. The page carries a photograph of Shinkichi Miki presenting a $5,000 donation on behalf of the Japan Business Association to Nisei Week Foundation president Mark Nakagawa.',
     'rafu shimpo japanese american newspaper los angeles little tokyo 71st nisei week japanese festival foundation donation']),

dict(path='掲載記事/group-nextage-no9-communication-tmm-los-angeles.pdf',
 keys=[], date='2009-01-01', group='掲載記事',
 title='Group Nextage No.9「コミュニケーション 言葉は違えど」TMM米国支店ロサンゼルス駐在員 三木晋吉',
 note='東京海上グループ社内報 Group Nextage 第9号 p.6。Tokio Marine Management, Inc.（TMM）米国支店（在ロサンゼルス）駐在員として、海外駐在12年目・3回目を迎えた立場から異文化コミュニケーションを語る。心掛けている3点として「自ら明るく積極的に」「表現はシンプルかつ丁寧に」「相手の立場に立って話をしっかりと聞く」を挙げ、TMM LAオフィスのスローガン「お客様と最高の関係を築く」に触れる。紹介者の池田博之氏は三木の「傾聴」の姿勢をコメント。職場の同僚との写真を掲載。',
 en=["Piece in Group Nextage No. 9, p. 6, the internal magazine of the Tokio Marine Group. Writing as a Los Angeles-based employee of Tokio Marine Management, Inc. (TMM) in his twelfth year abroad across three postings, Miki sets out three things he keeps in mind when working across cultures: approaching others openly and actively, keeping expression simple and courteous, and listening from the other person's position. He connects these to the TMM Los Angeles office slogan of building the best possible relationship with clients. A colleague's comment describes his habit of listening closely.",
     'group nextage internal magazine tokio marine management los angeles cross cultural communication listening expatriate 2009']),

dict(path='掲載記事/mobile-2002-spring-mobile-work-style.pdf',
 keys=[], date='2002-04-01', group='掲載記事',
 title='Mobile! 2002年春号「モバイルが仕事を変える！」用途に応じて自在にツールを使い分け',
 note='モバイル情報誌 Mobile! 2002年春号 p.104 の特集記事。東京海上火災保険 三木晋吉（37歳）が、上級者のモバイル環境について語る。中学時代からコンピュータに親しみ、学生時代にノートPCとメールアドレスを同時に入手。PDA・ノートPC・携帯電話を顧客訪問や移動の場面ごとに使い分ける手法、海外出張時のSIMカード運用、セキュリティへの配慮などを紹介。あわせてフリーソフト ClosePopup、BeerGuard を掲載。',
 en=['Feature in the Japanese magazine Mobile!, spring 2002 issue, p. 104. Shinkichi Miki, then 37 and working for Tokio Marine, describes an advanced mobile working setup: familiarity with computers since junior high, acquiring a laptop and an email address as a student, and switching between PDA, laptop and mobile phone according to whether he is visiting clients or travelling, along with SIM card use on overseas trips and his approach to security.',
     'mobile magazine 2002 pda laptop mobile phone work style sim card overseas business travel tokio marine tokyo']),

dict(path='記念写真/tokio-marine-malayan-insurance-manila-1990s.pdf',
 keys=[], date='1999-01-01', group='記念写真',
 title='Tokio Marine Malayan Insurance 社名変更記念パーティー（マニラ・1990年代後半）',
 note='東京海上のフィリピン現地法人 Tokio Marine Malayan Insurance Co., Inc. の社名変更を記念して開かれたパーティーの記録3点。会場に掲げられた横断幕には 「TOKIO MARINE MALAYAN INSURANCE CO., INC.（Formerly Pan Malayan Insurance Corp.）Honoring the Visit of Mr. Higuchi and Celebrating the Change of Corporate Name」とあり、本社からの来訪にあわせて、パン・マラヤン・インシュアランスからの社名変更を祝う会であったことが読み取れます。東京海上のフィリピン進出は1964年、ユチェンコ財閥のマラヤン・グループとの合弁によるものでした。当時の東京海上火災保険の社長は樋口公啓氏（在任1996年〜2001年）です。三木晋吉は選手生活を終えた直後の1990年代後半から5年間、マニラに駐在しました。収録は、横断幕の前での参加者の集合写真、邸宅での記念撮影、そしてマニラのオフィスで社長席を囲んだ一枚。フィルム写真をスキャンしたもので、撮影年月日の記録は残っていません。なお同社は2008年7月にマラヤン・インシュアランスに吸収合併され、社名としては姿を消しています。ご一緒した方々のお名前は伏せています。',
 en=['Three photographs from the party held to mark the change of corporate name of Tokio Marine\'s Philippine company, Tokio Marine Malayan Insurance Co., Inc. The banner in the hall reads "TOKIO MARINE MALAYAN INSURANCE CO., INC. (Formerly Pan Malayan Insurance Corp.) Honoring the Visit of Mr. Higuchi and Celebrating the Change of Corporate Name" — the evening joined a visit from the Tokyo head office with the retirement of the old name, Pan Malayan Insurance. Tokio Marine had entered the Philippine market in 1964 through a joint venture with the Malayan Group of the Yuchengco family; the president of Tokio Marine in this period was Koukei Higuchi, who held the office from 1996 to 2001. Shinkichi Miki was posted to Manila for five years from the late 1990s, directly after his playing career ended. The set holds the group portrait before the banner, a portrait at a residence, and one taken around the president\'s desk at the Manila office. These are scans of film prints and no date was recorded with them. The company itself was absorbed into Malayan Insurance in July 2008 and the name has since disappeared. The names of those pictured are withheld.',
     'tokio marine malayan insurance manila philippines pan malayan insurance corporation change of corporate name party higuchi yuchengco malayan group 1964 joint venture late 1990s film photographs shinkichi mike miki manila posting フィリピン マニラ 社名変更 樋口公啓']),

dict(path='競技歴/basketball-career-waseda-tokio-marine-1986-1997.pdf',
 keys=[], date='1997-11-26', group='競技歴',
 title='バスケットボール競技歴 1986-1997（早稲田大学・東京海上・マニラ）',
 note='バスケットボール選手時代の資料8点。第44回早慶バスケットボール定期戦（1986年6月15日 早稲田大学記念会堂）プログラム表紙。早稲田大学バスケットボール部 強化リーグB-1 選手名鑑（背番号7・センター・192cm・商学部・早大学院出身「シュート。走るセンターとして期待」）。日本リーグ（現Bリーグ）東京海上ビッグブルー 選手名鑑2年度分（背番号13・193cm・85kg・ロサンゼルス出身・杉並区立高井戸第三小→杉並区立向陽中→早稲田大学高等学院→早稲田大学、1991年は平均年齢27.6歳・平均身長187.5cmのチーム）。日本リーグ（現Bリーグ）の戦評およびスコア一覧2点。The Daily MANILA SHIMBUN 1997年11月26日「ひと交差点」日本人フィエスタのバスケで活躍・スポーツ通し日比交流に努力。',
 en=["Eight items from his playing years. The programme cover for the 44th Waseda-Keio basketball fixture, 15 June 1986. A Waseda University squad listing (No. 7, centre, 192cm, School of Commerce). Two seasons of squad listings for Tokio Marine Big Blue in Japan's national league, the forerunner of today's B.LEAGUE (No. 13, 193cm, 85kg, born in Los Angeles; the 1991 side averaged 27.6 years and 187.5cm). League match reports and two pages of scores. And an article in The Daily MANILA SHIMBUN, 26 November 1997, on his play at a Japanese community fiesta in the Philippines and his work on Japan-Philippine exchange through sport.",
     'basketball career waseda university tokio marine big blue falcon division japan league b.league bリーグ manila philippines daily manila shimbun center number 7 number 13 1991 squad']),

]

IMAGES = [
dict(path='掲載記事/mike-shinkichi-miki-a-day-bulletin-504-cover-2017.jpg',
 date='2017-09-18', group='掲載記事',
 title='三木晋吉 ポートレート（a day BULLETIN 第504号 表紙写真・2017年）',
 note='タイの週刊フリーマガジン a day BULLETIN 第504号（2017年9月18日発行）の表紙に使われたポートレート。当時、東京海上日動火災保険（タイランド）社長 三木晋吉（Shinkichi Mike Miki）。同誌はタイ全土に25万部を発行し、第504号の特集タイトルは「To Be a Good Company」。撮影は2017年8月11日、バンコクのスタジオにて。撮影：a day BULLETIN（TODAY EXPRESS）。',
 en=['The portrait used on the cover of a day BULLETIN No. 504, dated 18 September 2017 — a weekly free magazine distributed across Thailand with a circulation of 250,000 copies, whose feature for that issue was titled "To Be a Good Company." Shinkichi Mike Miki was then President of Tokio Marine Insurance (Thailand). Photographed in a Bangkok studio on 11 August 2017. Photograph by a day BULLETIN (TODAY EXPRESS).',
     'shinkichi mike miki 三木晋吉 portrait a day bulletin 504 cover 2017 to be a good company tokio marine insurance thailand president bangkok studio free magazine 250,000']),

dict(path='掲載記事/mike-shinkichi-miki-a-day-bulletin-504-portrait-bangkok-2017.jpg',
 date='2017-08-11', group='掲載記事',
 title='三木晋吉 誌面用ポートレート（バンコクのオフィスにて・2017年）',
 note='a day BULLETIN 第504号の特集インタビューに使われた誌面用ポートレート。2017年8月11日、バンコクの東京海上日動火災保険（タイランド）オフィスにて撮影。当時の社長 三木晋吉（Shinkichi Mike Miki）。撮影：a day BULLETIN（TODAY EXPRESS）。',
 en=['The portrait used inside the feature interview in a day BULLETIN No. 504, taken in the Bangkok office of Tokio Marine Insurance (Thailand) on 11 August 2017. Shinkichi Mike Miki was then President of the company. Photograph by a day BULLETIN (TODAY EXPRESS).',
     'shinkichi mike miki 三木晋吉 portrait bangkok office 2017 a day bulletin 504 feature interview tokio marine insurance thailand president black and white']),

dict(path='競技歴/mike-shinkichi-miki-tokio-marine-thailand-basketball-tournament.jpg',
 date='2015-01-01', group='競技歴',
 title='保険会社バスケットボール大会 出場（タイ・2015年）',
 note='2015年、タイ国東京海上火災保険 社長在任中に保険会社のバスケットボール大会へ出場した際の記念写真。中央で TOKIO MARINE INSURANCE GROUP の看板を持つ、最も背の高い人物が三木晋吉（左から6人目）。ご一緒した方々のお名前は伏せています。',
 en=['A team photograph from an insurance industry basketball tournament in Thailand in 2015, played while Shinkichi Miki was President of Tokio Marine Insurance (Thailand). He is the tallest figure at the centre, sixth from the left, holding the Tokio Marine Insurance Group board. The names of those pictured are withheld.',
     'shinkichi mike miki 三木晋吉 tokio marine insurance thailand basketball tournament bangkok 2015 corporate league team photograph president']),

dict(path='競技歴/mike-shinkichi-miki-manila-japanese-school-basketball-2000.jpg',
 date='2000-12-16', group='競技歴',
 title='マニラ日本人学校でのバスケットボール指導（2000年）',
 note='2000年12月16日、フィリピン駐在時にマニラ日本人学校で子どもたちにバスケットボールを指導した際の記念写真。後列左手、黒いTシャツを着た最も背の高い人物が三木晋吉。同じ月の12月3日に体育館でシュートを放つ一枚も本アーカイブに収めています。本アーカイブの競技歴に収めた The Daily MANILA SHIMBUN 1997年11月26日の記事でも、スポーツを通じた日比交流の取り組みが紹介されています。ご一緒した方々のお名前は伏せています。',
 en=['A group photograph taken on 16 December 2000 at the Manila Japanese School, where Shinkichi Miki coached basketball for the children during his posting to the Philippines. He is the tallest figure at the back left, in a black T-shirt. A frame of him shooting in the same gymnasium on 3 December of that month is also held in this archive. The article in The Daily Manila Shimbun of 26 November 1997, also held in this archive, describes his work on Japan-Philippine exchange through sport. The names of those pictured are withheld.',
     'shinkichi mike miki 三木晋吉 manila japanese school basketball coaching children philippines 2000 japan philippine exchange through sport expatriate']),

dict(path='競技歴/mike-shinkichi-miki-manila-japanese-school-basketball-shooting-2000.jpg',
 date='2000-12-03', group='競技歴',
 title='マニラ日本人学校の体育館でシュートを放つ三木晋吉（2000年12月3日）',
 note="2000年12月3日、フィリピン駐在時のマニラ日本人学校の体育館。シュートを放つ黒いTシャツの人物が三木晋吉です。子どもたちや保護者が入り交じってボールを追う練習の一場面で、写真の右下にはフィルムカメラの日付が「'00 12 3」と焼き込まれています。同じ月の12月16日に撮影した指導の記念写真も本アーカイブに収めています。ご一緒した方々のお名前は伏せています。",
 en=['The gymnasium of the Manila Japanese School on 3 December 2000, during Shinkichi Miki\'s posting to the Philippines. The figure releasing the shot, in the black T-shirt, is Miki. Children and parents share the floor in a practice session; the film camera\'s date stamp, "\'00 12 3", is burned into the lower right of the frame. The group photograph of the coaching taken on 16 December of the same month is also held in this archive. The names of those pictured are withheld.',
     'shinkichi mike miki 三木晋吉 manila japanese school basketball gymnasium shooting jump shot 3 december 2000 philippines coaching children expatriate film photograph date stamp マニラ日本人学校 バスケットボール']),

dict(path='競技歴/mike-shinkichi-miki-tokio-marine-big-blue-rebound.jpg',
 date='1991-01-01', group='競技歴',
 title='三木晋吉 東京海上ビッグブルー 背番号13（日本リーグ・1991年）',
 note='日本リーグ（現Bリーグ）東京海上ビッグブルー、1991年の一戦。ボールを競る背番号13が三木晋吉。同チームでの背番号13は競技歴の選手名鑑にも記載があります。月刊バスケットボール掲載。',
 en=["A contested rebound in a 1991 match played by Tokio Marine Big Blue in Japan's national league, the forerunner of today's B.LEAGUE. The player wearing No. 13 is Shinkichi Miki; the squad listings in the career PDF record him at that number. Published in Monthly Basketball (月刊バスケットボール).",
     'shinkichi mike miki 三木晋吉 tokio marine big blue number 13 japan basketball league b.league rebound action photograph 1991 corporate league monthly basketball 月刊バスケットボール']),

dict(path='競技歴/mike-shinkichi-miki-waseda-keio-1986-basketball.jpg',
 date='1986-06-15', group='競技歴',
 title='三木晋吉 早稲田大学バスケットボール部（第44回早慶戦・1986年）',
 note='第44回早慶バスケットボール定期戦（1986年6月15日 早稲田大学記念会堂）のプログラム表紙。シュートを放つ背番号11が早稲田大学バスケットボール部の三木晋吉。表紙写真は月刊バスケットボール提供。競技歴のPDFにも同じ表紙を収めていますが、画像として探せるよう独立して掲載しています。',
 en=['Cover of the programme for the 44th Waseda-Keio basketball fixture, played at the Waseda University Memorial Hall on 15 June 1986. The player shooting, No. 11, is Shinkichi Miki of the Waseda University basketball team. Cover photograph courtesy of Monthly Basketball. The same cover appears in the career PDF; it is published here separately so that it can be found as an image.',
     'shinkichi mike miki 三木晋吉 waseda university basketball 44th waseda keio game 1986 memorial hall number 11 programme cover college basketball japan monthly basketball 月刊バスケットボール']),

dict(path='競技歴/mike-shinkichi-miki-waseda-university-1986-free-throw.jpg',
 date='1986-01-01', group='競技歴',
 title='三木晋吉 早稲田大学バスケットボール部 背番号5（大学4年時・1986年）',
 note='早稲田大学バスケットボール部4年時、フリースローを放つ背番号5が三木晋吉。1986年（大学4年時）。月刊バスケットボール掲載。撮影日および大会名は確認できていません。ご一緒した方々のお名前は伏せています。',
 en=['Shinkichi Miki, No. 5, at the free-throw line in his fourth year with the Waseda University basketball team, 1986. Published in Monthly Basketball (月刊バスケットボール). Neither the exact date nor the competition has been confirmed. The names of those pictured are withheld.',
     'shinkichi mike miki 三木晋吉 waseda university basketball team number 5 free throw 1986 fourth year college basketball japan monthly basketball 月刊バスケットボール']),

]

VIDEOS = [
dict(path='王室関連/sirindhorn-royal-audience-2015-ch7-news.mp4',
 date='2015-11-04', group='王室関連', thumb_at=31,
 title='シリントーン王女殿下への拝謁 — チャンネル7 王室ニュース（2015年11月4日）',
 note='2015年11月4日、シリントーン王女殿下がタイ国東京海上火災保険の一行に拝謁を賜り、同社の寄付に対する表彰をお授けになりました。その様子を報じたタイのチャンネル7（ช่อง 7）の王室ニュース（ข่าวในพระราชสำนัก、同日19時48分放送）から、本件の該当部分38秒を収めています。番組タイトル、スタジオでの読み上げ、会場となった宮殿の外観、そして一行が順に拝謁する場面まで。三木晋吉はタイ国東京海上火災保険の社長として出席しました。同じ日の記念写真は本アーカイブの別項目に収めています。ご一緒した方々のお名前は伏せています。',
 en=["On 4 November 2015 Her Royal Highness Princess Maha Chakri Sirindhorn granted an audience to a delegation from Tokio Marine Insurance (Thailand) and conferred a commendation for the company's donation. This is the thirty-eight second portion reporting the occasion from the Royal Court News (ข่าวในพระราชสำนัก) broadcast by Channel 7 of Thailand at 19:48 that evening: the programme title, the studio read, the exterior of the palace where the audience was held, and the delegation received one by one. Shinkichi Miki attended as President of Tokio Marine Insurance (Thailand). Photographs from the same day are held as a separate item in this archive. The names of those pictured are withheld.",
     'princess maha chakri sirindhorn royal audience 4 november 2015 thailand tokio marine insurance donation commendation channel 7 ch7 royal court news broadcast palace bangkok shinkichi mike miki シリントーン王女 拝謁 タイ王室 チャンネル7 王室ニュース']),

]
